name: Documentation

on:
  push:
    branches: [ master ]

jobs:
  doc:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      name: Install toolchain
      with:
        # Targeting LKG nightly toolchain to produce documentation
        #
        # See https://github.com/imxrt-rs/imxrt-async-hal/runs/1465617955?check_suite_focus=true
        # for an example of a failing documentation run on a more-recent nightly
        # toolchain. TODO make sure that this doesn't become too stale!
        toolchain: nightly-2020-11-24
        target: thumbv7em-none-eabihf
        override: true

    - name: Generate docs
      run: cargo rustdoc --features imxrt1060 --features rt --target thumbv7em-none-eabihf -- --cfg docsrs

    - name: Write redirect
      run: echo "<meta http-equiv=\"refresh\" content=\"0;url=imxrt_async_hal\">" > target/thumbv7em-none-eabihf/doc/index.html

    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/thumbv7em-none-eabihf/doc
        publish_branch: gh-pages
