name: Documentation

on:
  push:
    branches: [ master ]

jobs:
  doc:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      name: Install toolchain
      with:
        toolchain: nightly
        target: thumbv7em-none-eabihf
        override: true

    - name: Generate docs
      run: cargo rustdoc --features imxrt1060 --features rt --target thumbv7em-none-eabihf -- --cfg docsrs

    - name: Write redirect
      run: echo "<meta http-equiv=\"refresh\" content=\"0;url=imxrt_async_hal\">" > target/thumbv7em-none-eabihf/doc/index.html

    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/thumbv7em-none-eabihf/doc
        publish_branch: gh-pages
